export const EXERCISES = [
    "Squat",
    "Deadlift",
    "Bench Press",
    "Shoulder Press",
    "Pull-Ups",
    "Push-Ups",
    "Dumbbell Rows",
    "Leg Press",
    "Lunges",
    "Bicep Curls",
    "Tricep Extensions",
    "Plank",
    "Crunches",
    "Leg Curls",
    "Leg Extensions",
    "Dips",
    "Chest Flyes",
    "Seated Rows",
    "Lat Pulldowns",
    "Arnold Press",
    "Hammer Curls",
    "Incline Bench Press",
    "Calf Raises",
    "Glute Bridges",
    "Reverse Lunges",
    "Bent Over Rows",
    "Side Raises",
    "Cable Curls",
    "Skull Crushers",
    "Box Jumps",
    "Romanian Deadlifts",
    "Decline Bench Press",
    "Tricep Dips",
    "Front Squats",
    "Barbell Rows",
    "Preacher Curls",
    "Upright Rows",
    "Kettlebell Swings",
    "Side Plank",
    "Leg Raises",
    "Dumbbell Flyes",
    "Barbell Curls",
    "Lateral Lunges",
    "Chin-Ups",
    "Seated Calf Raises",
    "Dumbbell Pullovers",
    "Cable Rows",
    "Concentration Curls",
    "Bench Dips",
    "Good Mornings",
    "Face Pulls",
    "Cable Crossovers",
    "Lateral Raises",
    "Leg Adductions",
    "Barbell Shrugs",
    "Cable Crunches",
    "Hip Thrusts",
    "Farmers Walk",
    "Plank with Leg Lift",
    "Barbell Lunges",
    "Smith Machine Squats",
    "Weighted Dips",
    "Cable Leg Curls",
    "Cable Face Pulls",
    "Hack Squats",
    "Pec Flyes",
    "Reverse Flyes",
    "Barbell Wrist Curls",
    "Dumbbell Lunges",
    "Weighted Crunches",
    "Push Press",
    "Weighted Push-Ups",
    "Knee Raises",
];
