export const EXERCISES = [
    "Squat",
    "Deadlift",
    "Bench Press",
    "Shoulder Press",
    "Pull-Ups",
    "Push-Ups",
    "Dumbbell Rows",
    "Leg Press",
    "Lunges",
    "Bicep Curls",
    "Tricep Extensions",
    "Plank",
    "Crunches",
    "Russian Twists",
    "Leg Curls",
    "Leg Extensions",
    "Dips",
    "Chest Flyes",
    "Seated Rows",
    "Lat Pulldowns",
    "Arnold Press",
    "Hammer Curls",
    "Incline Bench Press",
    "Calf Raises",
    "Glute Bridges",
    "Reverse Lunges",
    "Bent Over Rows",
    "Side Raises",
    "Cable Curls",
    "Skull Crushers",
    "Box Jumps",
    "Romanian Deadlifts",
    "Decline Bench Press",
    "Tricep Dips",
    "Front Squats",
    "Barbell Rows",
    "Close Grip Bench Press",
    "Preacher Curls",
    "Single-Leg Deadlifts",
    "Upright Rows",
    "Kettlebell Swings",
    "Side Plank",
    "Leg Raises",
    "Dumbbell Flyes",
    "Barbell Curls",
    "Lateral Lunges",
    "Chin-Ups",
    "Seated Shoulder Press",
    "Seated Calf Raises",
    "Dumbbell Pullovers",
    "Step-Ups",
    "Russian Deadlifts",
    "Cable Rows",
    "Concentration Curls",
    "Bench Dips",
    "Good Mornings",
    "Face Pulls",
    "Cable Crossovers",
    "Leg Raises on Dip Bars",
    "Incline Dumbbell Press",
    "Lateral Raises",
    "Leg Adductions",
    "Bulgarian Split Squats",
    "Barbell Shrugs",
    "Cable Crunches",
    "Hip Thrusts",
    "Farmers Walk",
    "Arnold Dumbbell Press",
    "Plank with Leg Lift",
    "Decline Dumbbell Flyes",
    "Roman Chair Leg Raises",
    "Incline Dumbbell Curls",
    "Reverse Grip Pulldowns",
    "Barbell Lunges",
    "Cable Rope Hammer Curls",
    "Smith Machine Squats",
    "Weighted Dips",
    "Cable Leg Curls",
    "Seated Incline Bench Press",
    "Cable Face Pulls",
    "Hammer Strength Chest Press",
    "Cable Tricep Pushdowns",
    "Hack Squats",
    "Pec Flyes",
    "Reverse Flyes",
    "Barbell Wrist Curls",
    "Reverse Grip Bench Press",
    "Dumbbell Lunges",
    "Weighted Crunches",
    "Dumbbell Pullovers on Stability Ball",
    "Push Press",
    "Cable Crunches on Knees",
    "EZ Bar Curls",
    "Weighted Push-Ups",
    "Knee Raises",
    "Decline Dumbbell Bench Press",
    "Dumbbell Hammer Curls",
    "Cable Bent Over Rows",
    "Close Grip Lat Pulldowns",
    "Single-Arm Dumbbell Rows",
];
